name: Deployment

on:
  push:
    branches: [ master ]


jobs:

  
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
          

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
     
     
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install dependencies
      run: |
       python -m pip install --upgrade pip
       pip install build
       pip install pyinstaller
       pip install pipreqs
       pip install opencv-python
   #Java Packages Environment
   
    - name: get jutil and add to path
      if: runner.os != 'Windows' 
      run: |
       git clone https://github.com/hasanhg/jutil.git && cd jutil && go build
       
    - name: add jutil to path
      if: runner.os != 'Windows'
      run: | 
       cp jutil/jutil /usr/local/bin
       cd /usr/local/bin && chmod +x jutil 
       echo "usr/local/bin" >> $GITHUB_PATH
       
    - name: get jutil and add to path
      if: runner.os == 'Windows' 
      run: |
       git clone https://github.com/hasanhg/jutil.git && cd jutil && go build && mv jutil.exe ../
       
    - name: Get jar
      run: curl -O -L https://storage.googleapis.com/rohat-repository/robomotion-1.3.jar
    
    - name: mvn install
      run: mvn install:install-file -Dfile="./robomotion-1.3.jar" -DgroupId="com.robomotion.app" -DartifactId="robomotion" -Dversion="1.3" -Dpackaging="jar"
      
    - name: Get jdk
      if: runner.os == 'Windows'
      run: curl -O -L https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jre_x64_windows_hotspot_11.0.11_9.zip
 
    - name: Get jdk
      if: runner.os == 'Linux'
      run: curl -O -L https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jre_x64_linux_hotspot_11.0.11_9.tar.gz
 
    - name: Get jdk
      if: runner.os == 'macOS'
      run: curl -O -L https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jre_x64_mac_hotspot_11.0.11_9.tar.gz
      
    - name: delete unnecessary directory
      if: runner.os == 'Windows'
      run: rd /s /q ".\jutil"
      shell: cmd
      
    - name: delete unnecessary directory
      if: runner.os != 'Windows'
      run:  rm -r jutil/
 
   #End of Java Packages Environment   
   
   
    - name: rclone and roboctl for linux
      if: runner.os == 'Linux'
      run: |
       curl -O -L https://storage.googleapis.com/rohat-repository/roboctl
       curl https://rclone.org/install.sh | sudo bash
       mkdir /home/runner/.config/rclone
  
    - name: rclone and roboctl for mac
      if: runner.os == 'macOS'
      run: |
       curl -L -o roboctl https://storage.googleapis.com/rohat-repository/roboctlmac 
       brew install rclone
       mkdir /Users/runner/.config/rclone
       
  
    - name: rclone and roboctl for windows
      if: runner.os == 'Windows'
      run: |
       C:\msys64\usr\bin\wget.exe -O roboctl https://storage.googleapis.com/rohat-repository/roboctlwin
       C:\msys64\usr\bin\wget.exe -O rclone.exe https://storage.googleapis.com/rohat-repository/rclone.exe
       mkdir C:/Users/runneradmin/AppData/Roaming/rclone
       
    - name: add to the path for windows
      if: runner.os == 'Windows'
      run: |
          echo "::add-path::${env:GITHUB_WORKSPACE}"
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true' 
        
    - name: add rclone.conf for windows
      if: runner.os == 'Windows' 
      run: 'echo "$SSH_KEY" >  C:/Users/runneradmin/AppData/Roaming/rclone/rclone.conf'
      shell: bash
      env:
        SSH_KEY: ${{secrets.RCLONE_CONF}}
        
    - name: add rclone.conf for mac
      if: runner.os == 'macOS' 
      run: 'echo "$SSH_KEY" >  /Users/runner/.config/rclone/rclone.conf'
      shell: bash
      env:
        SSH_KEY: ${{secrets.RCLONE_CONF}}
        
    - name: add rclone.conf for linux
      if: runner.os == 'Linux'
      run: 'echo "$SSH_KEY" >  /home/runner/.config/rclone/rclone.conf'
      shell: bash
      env:
        SSH_KEY: ${{secrets.RCLONE_CONF}}

        
    - name: rclone Get index.json from DO for Windows 
      if: runner.os == 'Windows'
      run: D:/a/packages-contrib/packages-contrib/rclone.exe copy -P DO:robomotion-packages/contrib/index.json .
      
    - name: rclone Get index.json from DO for Mac and Linux
      if: runner.os == 'macOS' || runner.os == 'Linux'
      run: rclone copy -P DO:robomotion-packages/contrib/index.json .
             
       
    - name: roboctl and permission for linux mac
      if: runner.os == 'macOS' || runner.os == 'Linux' 
      run: |
       cp roboctl /usr/local/bin
       cd /usr/local/bin && chmod +x roboctl 
       echo "usr/local/bin" >> $GITHUB_PATH
       
    - name: mkdir repo
      run: mkdir repo 
      
    - name: rclone repo
      if: runner.os == 'macOS' || runner.os == 'Linux' 
      run: rclone copy -P DO:robomotion-packages/contrib ./repo/
        
    - name: rclone repo windows   
      if: runner.os == 'Windows'
      run: D:/a/packages-contrib/packages-contrib/rclone.exe copy -P DO:robomotion-packages/contrib ./repo/
      
    - name: rclone repo macos   
      if: runner.os == 'macOS'
      run: rclone copy -P DO:robomotion-packages/contrib ./repo/
     
    - name: sudo
      if: runner.os == 'Linux'
      run: sudo chmod 777 -R  /home/runner/work/packages-contrib/packages-contrib/repo
      
    - name: go run build.go
      run: go run ./build.go 
      env:
          PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL: ${{ secrets.MAIL_USERNAME }}
          RUNNEROS: ${{ runner.os }}
 
      
        
    - name: rclone mono package windows   
      if: runner.os == 'Windows'
      run: D:/a/packages-contrib/packages-contrib/rclone.exe copy -P --s3-acl=public-read ./repo DO:robomotion-packages/contrib/
      
    - name: rclone mono package mac and linux   
      if: runner.os == 'macOS' || runner.os == 'Linux'
      run: rclone copy -P --s3-acl=public-read ./repo DO:robomotion-packages/contrib/
    
 
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    
    - name: rclone and roboctl for linux
      run: |
       curl -O -L https://storage.googleapis.com/rohat-repository/roboctl
       curl https://rclone.org/install.sh | sudo bash
       mkdir /home/runner/.config/rclone
       
    - name: roboctl and permission for linux
      run: |
       cp roboctl /usr/local/bin
       cd /usr/local/bin && chmod +x roboctl 
       echo "usr/local/bin" >> $GITHUB_PATH
       
       
    - name: repotopush
      run: mkdir repo
      
    - name: add rclone.conf for linux
      run: 'echo "$SSH_KEY" >  /home/runner/.config/rclone/rclone.conf'
      shell: bash
      env:
        SSH_KEY: ${{secrets.RCLONE_CONF}}
      
    - name: repo download
      run: rclone copy -P DO:robomotion-packages/contrib ./repo
      
    - name: chmod
      run: sudo chmod 777 -R  /home/runner/work/packages-contrib/packages-contrib/repo
        
        
    - name: roboctl index
      run: cd repo && roboctl repo index
      
    - name: repo upload
      run: rclone sync -P --s3-acl=public-read ./repo DO:robomotion-packages/contrib

    
